apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wc1y5ny4k-dotnet-basic
  janus-idp.io/tekton: wc1y5ny4k-dotnet-basic
  backstage.io/kubernetes-id: wc1y5ny4k-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wc1y5ny4k-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
